# ================================
# DeathWish Master Configuration
# Version: 1.0.3
# ================================

# ----------------
# Plugin Settings
# ----------------
settings:
  bstats:
    enabled: true     # Set to false if you want to disable anonymous usage metrics
  update-checker:
    enabled: true     # Checks for new plugin versions on startup
    notify-ops: true  # If true, operators will see update notifications on join

# ----------------
# General Settings
# ----------------
general:
  # Prefix shown before plugin messages
  prefix: "<gradient:#00FF00:#FFFFFF>[DeathWish] </gradient>"

  # Enable debug logs (extra console info)
  debug: false

  # Worlds where DeathWish is active
  enabled-worlds:
    - world
    - world_nether
    - world_the_end

  # How often difficulty multipliers are reapplied (ticks)
  difficulty-reapply-ticks: 6000 # 5 minutes

  # Enable/disable custom revive recipe system
  recipe-enabled: true

# ----------------
# Messages
# ----------------
messages:
  revive-broadcast: "<gradient:#00FF00:#FFFFFF>[DeathWish]</gradient> <gradient:#FF0000:#FFFFFF>{player}</gradient> <gradient:#00FF00:#FFFFFF>has been revived!</gradient>"
  not-dead: "<gradient:#FF0000:#FFFFFF>{player}</gradient> <gradient:#00FF00:#FFFFFF>is not dead.</gradient>"
  need-head: "<gradient:#00FF00:#FFFFFF>You must be holding</gradient> <gradient:#FF0000:#FFFFFF>{player}'s head</gradient> <gradient:#00FF00:#FFFFFF>to revive them.</gradient>"
  nobody-dead: "<gradient:#00FF00:#FFFFFF>There are no dead players at the moment.</gradient>"
  permadeath: "<gradient:#FF0000:#FFFFFF>{player}</gradient> <gradient:#00FF00:#FFFFFF>has fallen permanently... revive them, if you dare.</gradient>"
  cooldown-active: "<gradient:#00FF00:#FFFFFF>You must wait</gradient> <gradient:#FF0000:#FFFFFF>{time}</gradient> <gradient:#00FF00:#FFFFFF>before reviving again.</gradient>"
  revived-self: "<gradient:#00FF00:#FFFFFF>You successfully revived</gradient> <gradient:#FF0000:#FFFFFF>{player}</gradient><gradient:#00FF00:#FFFFFF>!</gradient>"
  deadlist-header: "<gradient:#00FF00:#FFFFFF>--- Dead Players ---</gradient>"
  deadlist-entry: "<gradient:#FF0000:#FFFFFF>➤ {player}</gradient>"
  deadlist-empty: "<gradient:#00FF00:#FFFFFF>No players are currently dead.</gradient>"

# ----------------
# Revive System
# ----------------
revive:
  # Global cooldown between revives (per player in seconds)
  cooldown-seconds: 86400 # 24 hours

  # Automatically revive dead players when they rejoin (if their head was crafted)
  revive-on-join: true

  # Storage (⚠️ do not edit manually unless you know what you’re doing)
  data:
    dead: []
    reviveTimestamps: {}

  # ----------------
  # Revive Recipe
  # ----------------
  recipe:
    # Recipe shape (3 lines, 3 chars each)
    shape:
      - "DDD"
      - "DND"
      - "DDD"

    # Keys that correspond to items
    keys:
      D: "DIAMOND"
      N: "NETHER_STAR"

    # Display name (supports MiniMessage)
    name: "<gradient:#00FF00:#FFFFFF>Revival Head:</gradient> <gradient:#FF0000:#FFFFFF>{player}</gradient>"

    # Lore (list of lines, MiniMessage supported)
    lore:
      - "<gradient:#00FF00:#FFFFFF>This head once belonged to</gradient> <gradient:#FF0000:#FFFFFF>{player}</gradient>"
      - "<gradient:#00FF00:#FFFFFF>Use it to restore their life.</gradient>"
      - "<gradient:#FF0000:#FFFFFF>⚠ One-time use ⚠</gradient>"

# ----------------
# Item & Loot Settings
# ----------------
items:
  # Default gradients for plugin-created items
  defaults:
    name-gradient: "<gradient:#00FF00:#FFFFFF>"
    lore-gradient: "<gradient:#FF0000:#FFFFFF>"

  # Toggle if crafted heads/lore can be overridden by config
  allow-custom-items: true

# ----------------
# Difficulty Scaling
# ----------------
difficulty:
  # Enable/disable difficulty multipliers globally
  enabled: true

  # Safety clamps to avoid runaway multipliers (set to 0 to disable)
  max-multiplier-health: 5.0
  max-multiplier-damage: 5.0

  # If true, only apply scaling to mobs defined in mobs.overrides (recommended)
  apply-only-overrides: false

  # If true, apply scaling at spawn time (recommended). If false, server will rely on applyDifficultyAll().
  apply-at-spawn: true

  # Default scaling applied to all mobs (feels like Hard+ mode)
  defaults:
    health-multiplier: 1.4
    damage-multiplier: 1.3

  # Global effects that apply to ALL mobs (immersive baseline buffs)
  global-effects:
    - "DAMAGE_RESISTANCE:0:99999"  # Slight toughness buff
    - "FAST_DIGGING:0:99999"       # Faster attack animations / reactions

  # Progressive scaling options
  scaling:
    time-based:
      enabled: true                # true = mobs scale with day count
      multiplier-per-day: 0.05     # +5% per Minecraft day

    death-based:
      enabled: true                # true = mobs scale with total player deaths
      multiplier-per-death: 0.1    # +10% per death

    boss-kill:
      enabled: true                # true = mobs scale once bosses are defeated
      multiplier-per-boss: 0.2     # +20% per boss kill

# ----------------
# Experimental Features
# ----------------
experimental:
  # Placeholder for future systems (scaling loot tables, event bosses, etc.)
  # Only read this after viewing source code and understanding this project.
  # This will only work if there are new features that are not released yet.
  enabled: false

# ----------------
# Passive Settings
# ----------------
passive-mobs:
  default:
    enabled: true
    health-multiplier: 1.5
    gradient-name: "<gradient:#00FF7F:#FFFFFF>{mob}</gradient>"
    effects: []
    custom-loot: []

  overrides:

    Bat:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#708090:#A9A9A9>Bat</gradient>"
      effects: []
      custom-loot: []

    Bee:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#FFDE00:#FFFF7F>Bee</gradient>"
      effects: []
      custom-loot: []

    Cat:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#FFFFFF:#CCCCCC>Cat</gradient>"
      effects: []
      custom-loot: []

    Chicken:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#FFFFF0:#FFD700>Chicken</gradient>"
      effects: []
      custom-loot: []

    Cow:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#8B4513:#D2691E>Cow</gradient>"
      effects: []
      custom-loot: []
    Donkey:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#DAA520:#FFD700>Donkey</gradient>"
      effects: []
      custom-loot: []

    Frog:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#00FF00:#32CD32>Frog</gradient>"
      effects: []
      custom-loot: []

    Goat:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#F5DEB3:#DEB887>Goat</gradient>"
      effects: []
      custom-loot: []

    Horse:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#CD853F:#DEB887>Horse</gradient>"
      effects: []
      custom-loot: []

    Mule:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#DAA520:#F4A460>Mule</gradient>"
      effects: []
      custom-loot: []

    Ocelot:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#FFD700:#FFE4B5>Ocelot</gradient>"
      effects: []
      custom-loot: []

    Pig:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#FFC0CB:#FF69B4>Pig</gradient>"
      effects: []
      custom-loot: []

    Rabbit:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#FFFFFF:#E0E0E0>Rabbit</gradient>"
      effects: []
      custom-loot: []

    Sheep:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#FFFFFF:#DDDDDD>Sheep</gradient>"
      effects: []
      custom-loot: []

    Turtle:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#20B2AA:#7FFFD4>Turtle</gradient>"
      effects: []
      custom-loot: []

    Villager:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#32CD32:#ADFF2F>Villager</gradient>"
      effects: []
      custom-loot: []

    Wolf:
      enabled: true
      health-multiplier: 1.5
      gradient-name: "<gradient:#A52A2A:#DEB887>Wolf</gradient>"
      effects: []
      custom-loot: []

# ----------------
# Hostile Settings 
# ----------------
mobs:
  default:
    enabled: true
    health-multiplier: 2.0
    damage-multiplier: 1.5
    gradient-name: "<gradient:#00FF00:#FFFFFF>{mob}</gradient>"
    effects: []
    custom-loot: []

  overrides:

    Blaze:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#FF6600:#FFCC00>Blaze</gradient>"
      effects: []
      custom-loot: []

    CaveSpider:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#00AA00:#55FF55>Cave Spider</gradient>"
      effects: []
      custom-loot: []

    Creeper:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#228B22:#ADFF2F>Creeper</gradient>"
      effects: []
      custom-loot: []

    Drowned:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#00CED1:#4682B4>Drowned</gradient>"
      effects: []
      custom-loot: []

    Enderman:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#551A8B:#9370DB>Enderman</gradient>"
      effects: []
      custom-loot: []
    Endermite:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#808080:#C0C0C0>Endermite</gradient>"
      effects: []
      custom-loot: []

    Ghast:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#F8F8FF:#FF6347>Ghast</gradient>"
      effects: []
      custom-loot: []

    Guardian:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#00BFFF:#1E90FF>Guardian</gradient>"
      effects: []
      custom-loot: []

    Hoglin:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#CD853F:#FF7F50>Hoglin</gradient>"
      effects: []
      custom-loot: []

    Husk:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#DAA520:#F5DEB3>Husk</gradient>"
      effects: []
      custom-loot: []

    MagmaCube:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#FF4500:#FF8C00>Magma Cube</gradient>"
      effects: []
      custom-loot: []

    Phantom:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#191970:#4169E1>Phantom</gradient>"
      effects: []
      custom-loot: []

    Piglin:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#FFD700:#FFA500>Piglin</gradient>"
      effects: []
      custom-loot: []

    Pillager:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#696969:#C0C0C0>Pillager</gradient>"
      effects: []
      custom-loot: []

    Shulker:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#BA55D3:#DA70D6>Shulker</gradient>"
      effects: []
      custom-loot: []

    Skeleton:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#C0C0C0:#FFFFFF>Skeleton</gradient>"
      effects: []
      custom-loot: []

    Slime:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#32CD32:#7CFC00>Slime</gradient>"
      effects: []
      custom-loot: []

    Spider:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#006400:#8FBC8F>Spider</gradient>"
      effects: []
      custom-loot: []

    Stray:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#ADD8E6:#E0FFFF>Stray</gradient>"
      effects: []
      custom-loot: []

    Vex:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#87CEEB:#B0E0E6>Vex</gradient>"
      effects: []
      custom-loot: []

    Witch:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#4B0082:#9400D3>Witch</gradient>"
      effects: []
      custom-loot: []

    WitherSkeleton:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#2F4F4F:#696969>Wither Skeleton</gradient>"
      effects: []
      custom-loot: []

    Zoglin:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#CD5C5C:#FA8072>Zoglin</gradient>"
      effects: []
      custom-loot: []

    Zombie:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#556B2F:#8FBC8F>Zombie</gradient>"
      effects: []
      custom-loot: []

    ZombieVillager:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#6B8E23:#9ACD32>Zombie Villager</gradient>"
      effects: []
      custom-loot: []

    ZombifiedPiglin:
      enabled: true
      health-multiplier: 2.0
      damage-multiplier: 1.5
      gradient-name: "<gradient:#FFD700:#CD853F>Zombified Piglin</gradient>"
      effects: []
      custom-loot: []

# ----------------
# Boss Settings
# ----------------
bosses:
  ENDER_DRAGON:
    enabled: true
    health-multiplier: 5.0
    damage-multiplier: 3.0
    gradient-name: "<gradient:#9400D3:#00FFFF>Abyssal Dragon</gradient>"
    abilities: []
    loot: []

  WARDEN:
    enabled: true
    health-multiplier: 5.0
    damage-multiplier: 3.0
    gradient-name: "<gradient:#191970:#00FF00>Downbad Warden</gradient>"
    abilities: []
    loot: []

  WITHER:
    enabled: true
    health-multiplier: 5.0
    damage-multiplier: 3.0
    gradient-name: "<gradient:#8B0000:#FF0000>Cataclysm Wither</gradient>"
    abilities: []
    loot: []

  ELDER_GUARDIAN:
    enabled: true
    health-multiplier: 5.0
    damage-multiplier: 3.0
    gradient-name: "<gradient:#00CED1:#1E90FF>Elder Sentinel</gradient>"
    abilities: []
    loot: []

  EVOKER:
    enabled: true
    health-multiplier: 5.0
    damage-multiplier: 3.0
    gradient-name: "<gradient:#FF4500:#FFD700>Grand Evoker</gradient>"
    abilities: []
    loot: []

  PIGLIN_BRUTE:
    enabled: true
    health-multiplier: 5.0
    damage-multiplier: 3.0
    gradient-name: "<gradient:#B22222:#FF8C00>Infernal Brute</gradient>"
    abilities: []
    loot: []

  VINDICATOR:
    enabled: true
    health-multiplier: 5.0
    damage-multiplier: 3.0
    gradient-name: "<gradient:#708090:#A9A9A9>Battle Vindicator</gradient>"
    abilities: []
    loot: []

  RAVAGER:
    enabled: true
    health-multiplier: 5.0
    damage-multiplier: 3.0
    gradient-name: "<gradient:#696969:#8B0000>Rampaging Ravager</gradient>"
    abilities: []
    loot: []
